apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  test.server: | # you may select any name here, but it must end with the .server file extension
    amordemaria.com:53 {
    log
    errors
    rewrite stop {
      name regex (.*)\.amordemaria.com {1}.default.svc.cluster.local
      answer name (.*)\.default\.svc\.cluster\.local {1}.amordemaria.com
    }
    forward . /etc/resolv.conf # you can redirect this to a specific DNS server such as 10.0.0.10, but that server must be able to resolve the rewritten domain name
    }