apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom # this is the name of the configmap you can overwrite with your changes
  namespace: kube-system
data:
    test.override: | # you may select any name here, but it must end with the .override file extension
          hosts { 
              10.0.0.1 amordemaria.com
              10.0.0.2 amordemaria.com
              10.0.0.3 amordemaria.com
              fallthrough
          }